version: 2.0


jobs:
  test:
    docker:
      - image: cimg/openjdk:16.0.0
    steps:
      - checkout
      - run: cd Scraper && mvn test

  build:
    docker:
      - image: cimg/openjdk:16.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
      - run: cd Scraper && mvn -Dmaven.test.skip=true package
      - save_cache:
            paths:
              - ~/.m2
            key: v1-dependencies-{{ checksum "pom.xml" }}
      - setup_remote_docker
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: cd Scraper && mvn clean install
            
workflows:
  version: 2

  build:
    jobs:
      - build:
          context: 
            - docker