version: 2.0


jobs:
  test:
    docker:
      - image: cimg/openjdk:16.0.0
        auth:
          username: ernesem
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run: cd Scraper && mvn test
      - run: cd Scraper && docker build . && docker push ernesem/delfinariumas:latest

  build:
    docker:
      - image: cimg/openjdk:16.0.0
        auth:
            username: ernesem
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run: cd Scraper && mvn clean install 
      - run: cd Scraper && docker build . && docker push ernesem/delfinariumas:latest


workflows:
  version: 2

  build:
    jobs:
      - build:
          context: 
            - docker

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build