version: 2.0


jobs:
  test:
    docker:
      - image: cimg/openjdk:16.0.0
    steps:
      - checkout
      - run: cd Scraper && mvn test

  build:
    docker:
      - image: cimg/openjdk:16.0.0
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: cd Scraper && mvn clean install
            
workflows:
  version: 2

  build:
    jobs:
      - build:
          context: 
            - docker

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build