version: 2.0


jobs:
  test:
    docker:
      - image: cimg/openjdk:16.0.0
        auth:
          username: ernesem
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: cd Scraper && mvn test

  build:
    docker:
      - image: cimg/openjdk:16.0.0
        auth:
            username: ernesem
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u ernesem --password-stdin
            cd Scraper && mvn clean install
            docker build .
            docker push ernesem/delfinariumas:latest


workflows:
  version: 2

  build:
    jobs:
      - build:
          context: 
            - docker

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build